CauchyE/telescope

.github/workflows/docker-cosmoscan.yml

close #36
@KimuraYu45z 
レビューお願いします。問題なさそうなら、mainブランチにマージしていただいた後、リリースタグ打って動作確認してみます。

feat: github actions to build docker image and push to docker hub

---

.github/workflows/docker-cosmoscan.yml

fix: github actions to remove unnecessary part of github.ref

---

.github/workflows/docker-cosmoscan.yml

close #36
@KimuraYu45z 
レビューお願いします。

fix: github actions to use environment variables

---

.github/workflows/docker-cosmoscan.yml

close #36 
@KimuraYu45z 
レビューお願いします！

fix: github actions to remove unnecessary npm run bundle and add cotext and file

---

projects/cosmoscan/src/view/app.component.html

close #43 
@KimuraYu45z 
未テスト機能のサイドメニューを隠す修正を加えました。レビューお願いします。

feat: hide untested side menu

---

.vscode/extensions.json

以下のextensionのおすすめ表示機能を追加してみました。
- Editor Config `editorconfig.editorconfig`
- Markdown Lint `davidanson.vscode-markdownlint`
- `docsmsft.docs-markdown`
- `docsmsft.docs-yaml`
- `ms-vsliveshare.vsliveshare`
- Markdown Preview Enhanced `shd101wyy.markdown-preview-enhanced`
- ESLint `dbaeumer.vscode-eslint`
- Prettier非推奨 `esbenp.prettier-vscode`
- Angular Language Service `angular.ng-template`
- Angular Schematics `cyrilletuzi.angular-schematics`
- stylelint `stylelint.vscode-stylelint`
- vscode-proto3 `zxh404.vscode-proto3`
- `toba.vsfire`
- tailwind `bradlc.vscode-tailwindcss`
- vscode-proto3 `zxh404.vscode-proto3`

feat: recommend extension

---

projects/cosmoscan/src/view/cosmos/bank/bank.component.html
projects/cosmoscan/src/view/cosmos/bank/send/send.component.html

close #48 
Bank画面にFunctionヘッダー、`Send Coin`にアイコン追加
Send画面のSendボタンを"accent"に着色
@YasunoriMATSUOKA 確認お願いします。

chore: send button color chages

---

.github/workflows/docker-cosmoscan.yml

@YasunoriMATSUOKA 私もうっかりしてました。修正ご確認ください。

fix: action trigger curl command

---

package-lock.json
package.json
projects/cosmoscan/src/app/accounts/account/account.component.html
projects/cosmoscan/src/app/accounts/account/account.component.ts
projects/cosmoscan/src/app/accounts/account/staking/staking.component.html
projects/cosmoscan/src/app/accounts/account/staking/staking.component.ts
projects/cosmoscan/src/view/accounts/account/account.component.html
projects/cosmoscan/src/view/accounts/account/account.component.ts
projects/cosmoscan/src/view/accounts/account/bank/bank.component.html
projects/cosmoscan/src/view/accounts/account/bank/bank.component.ts
projects/cosmoscan/src/view/accounts/account/bank/bank.module.ts
projects/cosmoscan/src/view/accounts/account/staking/staking.component.html
projects/cosmoscan/src/view/accounts/account/staking/staking.component.ts
projects/cosmoscan/src/view/accounts/account/staking/staking.module.ts

#65 
@KimuraYu45z レビューお願いします。
状況
以下情報をaccounts/{{accAddress}} ページで表示するように実装
- アカウント情報
- 残高
- バリデーター報酬
以下情報については、後程、別途対応
- デリゲーター報酬
- トランザクション履歴

[WIP] Staking earning info

---

projects/cosmoscan/src/view/accounts/account/account.component.ts

Publickeyの表示を修正
pub_keyフィールドをunpackAnyし、PubKeyインスタンスに変えて表示
@YasunoriMATSUOKA よろしくお願いします

fix: pub_key unpackAny

---

package-lock.json
package.json
projects/cosmoscan/src/app/accounts/account/account.component.ts
projects/cosmoscan/src/app/cosmos/bank/send/send.component.ts
projects/cosmoscan/src/model/cosmos/bank.application.service.ts
projects/cosmoscan/src/model/cosmos/bank.service.ts
projects/cosmoscan/src/model/cosmos/staking.application.service.ts
projects/cosmoscan/src/model/cosmos/staking.service.ts
projects/cosmoscan/src/model/keys/key.infrastructure.service.ts
projects/cosmoscan/src/view/accounts/account/account.component.ts
projects/cosmoscan/src/view/cosmos/bank/send/send.component.ts
projects/cosmoscan/src/view/cosmos/staking/delegators/create/create.component.ts

cosmos-client-ts v0.42.12の変更を反映しています。
@KimuraYu45z 問題ないか確認お願いします。

fix: proto namespace

---

projects/cosmoscan/src/app/accounts/account/account.component.html
projects/cosmoscan/src/app/accounts/account/staking/staking.component.html
projects/cosmoscan/src/app/accounts/account/staking/staking.component.ts
projects/cosmoscan/src/app/accounts/account/vesting/vesting.component.html
projects/cosmoscan/src/app/accounts/account/vesting/vesting.component.ts
projects/cosmoscan/src/app/accounts/accounts.module.ts
projects/cosmoscan/src/view/accounts/account/staking/staking.component.html
projects/cosmoscan/src/view/accounts/account/staking/staking.component.ts
projects/cosmoscan/src/view/accounts/account/vesting/vesting.component.html
projects/cosmoscan/src/view/accounts/account/vesting/vesting.component.ts
projects/cosmoscan/src/view/accounts/account/vesting/vesting.module.ts

close #77
バリデーター報酬をvestingコンテナに移し、stakingコンテナにデリゲーター報酬を記述し、表示させてみました。
デリゲート先が自身のアドレスしかないのですが、これは問題ないのでしょうか？
/accounts/jpyx10lcj22kzftvnduchatmnsnhfljeky5ghd398wt
@YasunoriMATSUOKA @KimuraYu45z レビューお願いします。

feat: delegator eaning

---

package-lock.json
package.json
projects/cosmoscan/src/app/app.module.ts
projects/cosmoscan/src/app/home/blocks/blocks.component.html
projects/cosmoscan/src/app/home/blocks/blocks.component.ts
projects/cosmoscan/src/app/home/home.component.html
projects/cosmoscan/src/app/home/home.component.ts
projects/cosmoscan/src/app/home/txs/txs.component.html
projects/cosmoscan/src/app/home/txs/txs.component.ts
projects/cosmoscan/src/view/home/blocks/blocks.component.html
projects/cosmoscan/src/view/home/blocks/blocks.component.ts
projects/cosmoscan/src/view/home/blocks/blocks.module.ts
projects/cosmoscan/src/view/home/home.component.html
projects/cosmoscan/src/view/home/home.component.ts
projects/cosmoscan/src/view/home/home.module.ts
projects/cosmoscan/src/view/home/txs/txs.component.html
projects/cosmoscan/src/view/home/txs/txs.component.ts
projects/cosmoscan/src/view/home/txs/txs.module.ts

close #78 #86
トップページにLatest Blocks表示を追加
コンポーネント、モジュールもblocksに変更しています。
Block HeightとTime stampを20件表示し、古いものから順に削除
Txも同様にできるかと思いますが、test chainにTx履歴がなくデータ構造が見れないので、来週にVPSの設定変更とともに対応します。

feat: latest block info on top page

---

projects/cosmoscan/src/app/home/home.component.html
projects/cosmoscan/src/app/home/txs/txs.component.ts
projects/cosmoscan/src/view/home/txs/txs.component.html
projects/cosmoscan/src/view/home/txs/txs.component.ts

latestBlocks同様にwebsocketで取得したlatestTxsをトップページに表示（最大20件）
@KimuraYu45z レビューお願いします。

feat: latest txs on top page

---

projects/cosmoscan/config.js.template
projects/cosmoscan/src/app/cosmos/gov/gov-routing.module.ts
projects/cosmoscan/src/app/cosmos/gov/gov.module.ts
projects/cosmoscan/src/app/cosmos/gov/proposals/proposal/proposal.component.html
projects/cosmoscan/src/app/cosmos/gov/proposals/proposal/proposal.component.ts
projects/cosmoscan/src/view/cosmos/gov/proposals/proposal/proposal.component.html
projects/cosmoscan/src/view/cosmos/gov/proposals/proposal/proposal.component.ts
projects/cosmoscan/src/view/cosmos/gov/proposals/proposal/proposal.module.ts

差分のみのPRです。
Proposal詳細画面を実装しました。
DepositorとVoterがないのでまだそこは未検証ですが、APIが同じなのでおそらく動くと思います。

Proposal detail

---

projects/cosmoscan/src/app/app.module.ts
projects/cosmoscan/src/app/home/distribution/distribution.component.html
projects/cosmoscan/src/app/home/distribution/distribution.component.ts
projects/cosmoscan/src/app/home/home.component.html
projects/cosmoscan/src/view/home/distribution/distribution.component.html
projects/cosmoscan/src/view/home/distribution/distribution.component.ts
projects/cosmoscan/src/view/home/distribution/distribution.module.ts

操作ミスのため、再掲
Community PoolをSupply同様にトップページに実装しました。

feat: community pool

---

projects/cosmoscan/src/view/home/blocks/blocks.component.css
projects/cosmoscan/src/view/home/blocks/blocks.component.html
projects/cosmoscan/src/view/home/txs/txs.component.css
projects/cosmoscan/src/view/home/txs/txs.component.html

close #108 
@KimuraYu45z @Senna46 @YasunoriMATSUOKA 
こちらスクロールバーを追加しました。
EthEthscanがスクロールする前に5項目と少し見えていたので、同じように作成しました。
レビューお願い致します。

fix: scroll-bar

---

projects/cosmoscan/src/view/home/blocks/blocks.component.html
projects/cosmoscan/src/view/home/txs/txs.component.html

`<h2>Latest Blocks</h2>`
タイトル部分までスクロールに入っている問題を修正
@Tomosuke0930 レビューお願いします

fix: scroll

---

projects/cosmoscan/src/app/app.component.ts

close #66 
検索バーの不具合箇所を偶然見つけたので修正。
formats: camelCase が要求されていたので，一応`txHash`という形式にしておきます。

fix: serch bar txHash

---

projects/cosmoscan/src/app/home/bank/bank.component.ts
projects/cosmoscan/src/app/home/blocks/blocks.component.html
projects/cosmoscan/src/app/home/blocks/blocks.component.ts
projects/cosmoscan/src/app/home/distribution/distribution.component.ts
projects/cosmoscan/src/app/home/txs/txs.component.ts
projects/cosmoscan/src/view/home/blocks/blocks.component.html
projects/cosmoscan/src/view/home/blocks/blocks.component.ts
projects/cosmoscan/src/view/home/txs/txs.component.html

@KimuraYu45z cc: @Senna46 @Tomosuke0930 
レビューお願いします。(最初は、APIを定期的に叩くポーリングや、最新ブロックから20ブロック程度さかのぼってブロック一覧のデータを取得するところまでまとめてやろうと思っていたのですが、consoleに大量に出ていたエラーがデバッグでかなり邪魔だったので、先にエラーの解消を優先しました。エラーの解消に思いのほか時間がかかってしまったため、いったんプルリク作成しておきます。作業としては、引き続き、ポーリングや、ブロックさかのぼってデータ取得する実装を進めておきますが、いったんこれでマージしてもよいかなと思っています。)
http://localhost:4200/ で表示されるページで、consoleに大量に表示されていたエラーを修正し、websocketの箇所をコメントアウトし、console.logを消しました。
- fix null slice error in view/home/txs.component.html
- comment out websocket
- remove console.log

fix: error, remove websocket and console

---

projects/cosmoscan/docker-compose.yml

https://github.com/lcnem/cosmoscan/issues/93

chore: network mode

---

projects/cosmoscan/src/app/home/txs/txs.component.ts
projects/cosmoscan/src/view/home/txs/txs.component.html

@KimuraYu45z cc: @Senna46 @Tomosuke0930 
すみませんが、先ほどの修正の際に、勢い余って、エラーだけでなく、Latest Txsの表示自体が消えてしまう状態にしてしまっていたのを修正しました。
レビューお願いします。

fix: latest txs are not shown

---

projects/cosmoscan/src/app/home/blocks/blocks.component.html
projects/cosmoscan/src/app/home/blocks/blocks.component.ts
projects/cosmoscan/src/view/home/blocks/blocks.component.html
projects/cosmoscan/src/view/home/blocks/blocks.component.ts
tsconfig.json

@KimuraYu45z cc: @Senna46 @Tomosuke0930 
最新ブロックから順に1ブロックずつ、各ブロックの情報を取得して表示する実装を加えました。
レビューお願いします。

feat: show blocks list on home blocks component

---

projects/cosmoscan/src/app/home/blocks/blocks.component.ts
projects/cosmoscan/src/app/home/txs/txs.component.ts

@KimuraYu45z cc: @Senna46 @Tomosuke0930 
5秒間に1回の周期で、LatestBlocksとLatestTxsのAPIを叩くよう、ポーリングの処理を追加しました。
意図通り、動作することを、ローカルで確認済です。
レビューお願いします。

feat: polling home blocks txs

---

projects/main/src/app/models/db.service.ts

@KimuraYu45z 
レビューお願いします。
ローカルでkeyのcreateや単純なコインのトランザクションは動作することを確認しました。

fix: index db name cosmoscan to telescope

---

projects/main/src/app/views/app.component.html

@YasunoriMATSUOKA さん
#133
こちらの実装完了しました。
ご確認のほどよろしくお願い致します。

fix: add-jpyx-side-navi

---

projects/main/src/app/app.component.ts
projects/main/src/app/models/config.service.ts

close #138 
@KimuraYu45z cc: @Senna46 @taro04 
レビューお願いします。

fix: faucet link config

---

.github/workflows/docker-monitor.yml
projects/main/src/app/models/monitor.service.ts
projects/main/src/app/pages/monitor/monitor.component.ts
projects/main/src/app/views/monitor/monitor.component.html
projects/monitor/monitor.go

取り急ぎview componentを修正しました。
@KimuraYu45z 
startの時間ですが、今日の日付を取得して、一日前の日付をstart_year, month, dayに入れるという実装で良いのでしょうか？

fix: view monitor

---

.github/workflows/docker-monitor.yml
projects/monitor/Dockerfile

#151
workflowファイルでの環境変数設定が効かなかったので、Dockerfile内での環境変数の受け渡しで試してみます

fix: go install

---

projects/main/config.js.template
projects/monitor/Dockerfile
projects/monitor/docker-compose.yml

デバッグ環境と合わせてport:9000でmonitorを動作させようと考えています。
(Well known portに800はないようですが念の為)
@YasunoriMATSUOKA 問題なければこれでマージさせてください。よろしくお願いします。

chore: monitor port setting

---

projects/main/src/app/models/monitor.service.ts
projects/main/src/app/pages/monitor/monitor.component.html
projects/main/src/app/pages/monitor/monitor.component.ts
projects/main/src/app/views/monitor/monitor.component.html
projects/main/src/app/views/monitor/monitor.component.ts
projects/main/src/app/views/monitor/monitor.module.ts
projects/monitor/main.go
projects/monitor/monitor.go

@KimuraYu45z @YasunoriMATSUOKA 
moniter画面において、mat-datepickerでのstart time選択、formでのcount選択を実装しました。
初期値では動くのですが、入力後の同期について、理解が及んでおらず実装できておりません。
お手すきのときにヘルプもらえると有り難いです。

feat: monitor form

---

projects/main/src/app/views/app.component.html

@KimuraYu45z cc: @taro04 @Senna46 
レビューお願いします。
すみませんが、しょうもないタイポでrouterLinkが正常にこのリンクだけ動作していませんでした...

fix: typo of routerlink

---

projects/main/src/app/pages/home/txs/txs.component.html
projects/main/src/app/pages/home/txs/txs.component.ts
projects/main/src/app/pages/txs/txs.component.ts
projects/main/src/app/views/home/txs/txs.component.html
projects/main/src/app/views/home/txs/txs.component.ts

homeのtxsの降順化について変更自体は終わってますが、APIが想定と異なる挙動をしていたため一部未完です。
進捗報告としてPR作成します。

feat: home_txs_descending_order

---

projects/main/src/app/views/keys/create/create.component.html

@KimuraYu45z cc: @taro04 @Senna46 
レビューお願いします。
ニーモニックがコピーされるべき箇所で誤って秘密鍵をコピーしていたというミスの修正となります。

feat: fix wrong copy value

---

projects/main/config.js.template

@KimuraYu45z cc: @taro04 @Senna46 
レビューお願いします。
jsmn -> jcbnの変更については、特に対応不要でしたが、config.js.templateの中に、faucetとmonitorの内容が記載されていなかったため、一応記載しておきました。(これはそもそもダミーファイルなので、この変更によって動作に影響はありません。)

fix: config js template

---

projects/main/src/app/views/app.component.ts

sidenavでページ遷移した後、sidenavが閉じるよう修正しました。ご確認お願いします。

feat: sidenav_aute_close

---

projects/main/src/app/views/blocks/block/block.component.html
projects/main/src/app/views/blocks/blocks.component.html
projects/main/src/app/views/cosmos/staking/validators/validators.component.html
projects/main/src/app/views/home/bank/bank.component.html
projects/main/src/app/views/home/blocks/blocks.component.html
projects/main/src/app/views/home/distribution/distribution.component.html
projects/main/src/app/views/home/distribution/distribution.component.ts
projects/main/src/app/views/home/home.component.html
projects/main/src/app/views/home/mint/mint.component.html
projects/main/src/app/views/keys/create/create.component.html
projects/main/src/app/views/keys/key/key.component.html
projects/main/src/app/views/txs/tx/tx.component.css
projects/main/src/app/views/txs/tx/tx.component.html
tailwind.config.js

作成途中ですが、確認のためPR作成します。
少数点６桁化は、htmlの{{　}}内でNumber( )が使えなかったので、自作の関数を定義しました。
ご確認お願い致します。問題なければ他にも展開します。

feat: fix_layout_for_mobile

---

projects/main/src/app/models/monitor.service.ts
projects/main/src/app/pages/monitor/monitor.component.html
projects/main/src/app/pages/monitor/monitor.component.ts
projects/main/src/app/views/monitor/monitor.component.html
projects/main/src/app/views/monitor/monitor.component.ts

@KimuraYu45z cc: @Senna46 @taro04 
日時報酬履歴のAPIがおそらく意図通り動いていないようだったため、APIをたたく回数は増えてしまいますが、各日付毎にAPIたたく形でワークアラウンドで対応しました。
レビューお願いします。
API自体の問題は以下の通りで、どこかで修正試みようと思います。
日時報酬履歴のAPIが、countが3以上の場合に3日分のデータを返すのが期待値であるにも関わらず2日分のデータしか返されていないように見えました。
例えば、以下APIのレスポンスの期待値は3日分のデータですが2日分しか返ってきていないように見えました。
http://a.test.jpyx.lcnem.net:9000/list?start_year=2021&start_month=10&start_day=20&count=3
```json
[
{
"before_date": "2021-10-20T00:00:00Z",
"date": "2021-10-21T00:00:00.000902029Z",
"result": {
"commission": {
"commission": {
"commission": [
{
"denom": "ujcbn",
"amount": "43387816.736250000000000000"
}
]
}
},
"outstanding_rewards": {
"rewards": {
"rewards": [
{
"denom": "ujcbn",
"amount": "433878167.362500000000000000"
}
]
}
}
}
},
{
"before_date": "2021-10-19T00:00:00Z",
"date": …
```

feat: fix-monitor-workaround

---

projects/monitor/docker-compose.yml

@KimuraYu45z 
レビューお願いします。
monitorのDBのデータが、Dockerコンテナ再起動でリセットされてしまう問題の修正、先ほど相談させてもらった内容のプルリクです。

fix: monitor db volume mount

---

projects/main/src/app/views/cosmos/staking/validators/validator/validator.component.html

@taro04 cc: @KimuraYu45z 
現在作成中のプルリク( https://github.com/lcnem/telescope/pull/198 )のブランチに対する修正提案です。
レビューして頂き、問題無ければ、Approveしてマージして作業進めてください。
- 可読性を高める意図でのコードスタイルの若干の修正(自分の環境ではこの書き方でLint問題無いように見えているのですが、もしLint問題あれば、ご指摘ください。)
- Unboundingはおそらく誤りで、Unbondingが正しいと思われる。

fix: lint and typo

---

projects/main/src/app/views/cosmos/staking/validators/validator/validator.component.html

バリデータページのレイアウト調整しました。
ご確認お願い致します。

feat: arrange validator page layout

---

.vscode/extensions.json
projects/main/src/app/pages/accounts/account/account.component.html
projects/main/src/app/pages/accounts/account/account.component.ts
projects/main/src/app/pages/accounts/account/distribution/distribution.component.html
projects/main/src/app/pages/accounts/account/distribution/distribution.component.ts
projects/main/src/app/pages/accounts/account/staking/staking.component.html
projects/main/src/app/pages/accounts/account/staking/staking.component.ts
projects/main/src/app/views/accounts/account/distribution/distribution.component.html
projects/main/src/app/views/accounts/account/distribution/distribution.component.ts
projects/main/src/app/views/accounts/account/staking/staking.component.html
projects/main/src/app/views/accounts/account/staking/staking.component.ts
projects/main/src/app/views/cosmos/staking/validators/validator/validator.component.html

質問と確認のため、PR作成します。（デバック用の回路も多数のこっています。）
■事象
存在しないアドレスを入力すると、非表示であるべき「Validator Rewards」以下のmat-cardが表示される。

feat: debug account info page

---

projects/main/src/app/models/keys/key.application.service.ts

[https://github.com/lcnem/telescope/issues/221](https://github.com/lcnem/telescope/issues/221)
コメントの通り実装しました。ローカルで動作確認しました。ご確認お願い致します。

feat: add account creation restriction

---

projects/main/src/app/views/home/txs/txs.component.html
projects/main/src/app/views/txs/txs.component.html

[https://github.com/lcnem/telescope/issues/216](https://github.com/lcnem/telescope/issues/216)
当該箇所を等倍フォントに修正しました。
txsページも同様に修正しています。
ご確認お願い致します。

feat: monospaced font

---

projects/main/src/app/models/cosmos/bank.application.service.ts
projects/main/src/app/models/cosmos/bank.model.ts
projects/main/src/app/models/cosmos/bank.service.ts
projects/main/src/app/models/cosmos/staking.application.service.ts
projects/main/src/app/models/cosmos/staking.service.ts
projects/main/src/app/pages/cosmos/staking/create-validator/create-validator.component.html
projects/main/src/app/pages/cosmos/staking/create-validator/create-validator.component.ts
projects/main/src/app/views/cosmos/staking/create-validator/create-validator.component.html
projects/main/src/app/views/cosmos/staking/create-validator/create-validator.component.ts

まだデバッグ未完ですが、ほぼ実装完了できたかなと思っています。一旦プルリク作成だけしておきます。
明日、 cosmos-sdk.next-web-technology.com をノードとして立ち上げて、create-validatorのトランザクションを実行して、デバッグして、問題無ければ、レビューをお願いすることにします。

feat: add simulation request to tx staking create validator

---

package-lock.json
package.json

@KimuraYu45z 
レビューお願いします。
cosmos-client-tsのバージョンアップ対応です。(telescope側には直接的な影響はないと思っていて、デバッグは軽めです。)

feat: bumps cosmos-client-ts from v0.44.3 to v0.44.4

---

.github/workflows/ci-docker-monitor.yml
.github/workflows/ci-docker-telescope.yml
.github/workflows/docker-monitor.yml
.github/workflows/docker-telescope.yml

@KimuraYu45z 
レビューお願いします。
- docker hub -> github packages container registry
- lcnem/botany -> UnUniFi/utils

fix: cd to migrate docker hub to github packages container registry

---

.github/workflows/ci-docker-monitor.yml
.github/workflows/ci-docker-telescope.yml
.github/workflows/docker-monitor.yml
.github/workflows/docker-telescope.yml

@KimuraYu45z 
レビューお願いします。
コンテナレジストリの名前の箇所は、大文字はNGのようだったので修正しました。

fix: container registry name

---

projects/main/docker-compose.yml
projects/monitor/Dockerfile
projects/monitor/README.md
projects/monitor/deploy.sh
projects/monitor/docker-compose.yml
projects/monitor/go.mod

@KimuraYu45z 
レビューお願いします。
monitorについて、CDは変更済だったのですが、それ以外の変更が漏れていたため、修正しました。

fix: monitor to ununifi

---

projects/main/src/app/pages/accounts/account/account.component.ts
projects/main/src/app/views/accounts/account/account.component.ts

close #244
@KimuraYu45z 
レビューお願いします。
これまでのテストネットには、Vesting Accountが存在せず、その場合が考慮されていなかったので、Vesting Accountの場合に無効なアドレス扱いされないよう、修正を加えました。

fix: vesting account info

---

projects/main/src/app/models/cosmos/bank.application.service.ts
projects/main/src/app/models/cosmos/bank.service.ts

[https://github.com/CauchyE/telescope/issues/245](https://github.com/CauchyE/telescope/issues/245)
のISSUE修正です。
以下参考に実装しました。
[https://www.nishishi.com/javascript-tips/trim-space-chars.html](https://www.nishishi.com/javascript-tips/trim-space-chars.html)
ローカル環境での動作確認と、コンソールへの出力で確認しました。
コンソール出力結果
ご確認お願い致します。

feat: deal with transaction that has some space characters

---

projects/main/src/app/models/cosmos/tx-common.service.ts

@KimuraYu45z 
レビューお願いします。
https://github.com/UnUniFi/utils/pull/177 の横展開です。

fix: show txhash before error message

---

projects/main/src/app/pages/accounts/account/account.component.html
projects/main/src/app/pages/accounts/account/txs/txs.component.html
projects/main/src/app/pages/accounts/account/txs/txs.component.ts
projects/main/src/app/pages/accounts/accounts.module.ts
projects/main/src/app/views/accounts/account/account.module.ts
projects/main/src/app/views/accounts/account/txs/txs.component.html
projects/main/src/app/views/accounts/account/txs/txs.component.ts
projects/main/src/app/views/accounts/account/txs/txs.module.ts

@KimuraYu45z @ThetaShis 
レビューお願いします。
以下のようなイメージでアカウント情報詳細ページに対象アカウントがsenderのトランザクション一覧を追加しました。本当はreceiverの時とか色々考えることあるかもですが、取り急ぎ今の問題に対応するには一旦これでOKかなと思っています。

feat: add txs list to account info page

---

projects/main/src/app/models/cosmos/bank.application.service.ts
projects/main/src/app/models/cosmos/staking.application.service.ts

@KimuraYu45z 
レビューお願いします。
以下hotfixのdevelopブランチへの反映です。
https://github.com/CauchyE/telescope/pull/252

feat: add loading dialog to simulation

---

projects/main/src/app/models/cosmos/bank.application.service.ts
projects/main/src/app/models/cosmos/bank.service.ts

@KimuraYu45z @taro04 
以下プルリクでレビュー済の内容なので、CI通ってコンフリクト無ければマージします。
https://github.com/CauchyE/telescope/pull/256

feat: remove unintentional whitespace in private key

---

projects/main/src/app/pages/blocks/blocks.component.html
projects/main/src/app/pages/blocks/blocks.component.ts
projects/main/src/app/views/blocks/blocks.component.html
projects/main/src/app/views/blocks/blocks.component.ts

@taro04 
https://github.com/CauchyE/telescope/pull/258 の件、動作としては問題解決されたと思います。ありがとうございました。
後は、(以前自分が実装したところで良くなかったなあと思った部分も含め、)変数名や、無効な場合のデータの処理(あまり意味のないダミー数値は思い切って全部undefinedに変更)や、デフォルト値のハードコードを一か所にまとめる等の修正提案を作成しました。
デバッグは甘めなので、問題無いかレビューして頂いて、問題無ければマージした上で(もし必要あれば)作業進めて頂ければと思います。
よろしくお願いします。

feat: fix proposal for hotfix pagination query

---

projects/main/src/app/models/cosmos/bank.service.ts
projects/main/src/app/models/keys/key.service.ts
projects/main/src/app/pages/keys/create/create.component.ts

@KimuraYu45z @taro04 
以下プルリクと同じ内容なので、CI通ってコンフリクト無ければそのままマージします。
https://github.com/CauchyE/telescope/pull/268

fix: remove whitespace in keyservice

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

@KimuraYu45z 
レビューお願いします。
Issueのテンプレート作成です。

hotfix: update issue templates

---

projects/main/src/app/models/faucets/faucet.application.service.ts
projects/main/src/app/models/faucets/faucet.infrastructure.service.ts
projects/main/src/app/models/faucets/faucet.service.ts
projects/main/src/app/pages/faucet/faucet.component.ts

https://github.com/CauchyE/telescope/issues/279
@YasunoriMATSUOKA 雑な自信があるので、仕様これでいいか確認お願いします。

hotfix: faucet error

---

projects/main/src/app/pages/home/bank/bank.component.ts
projects/main/src/app/pages/home/blocks/blocks.component.ts
projects/main/src/app/pages/home/home.component.ts
projects/main/src/app/pages/home/txs/txs.component.ts

緊急修正
intervalによる自動更新を事実上ないレベルまで間隔開けて負荷分散目的

feat: polling interval

---

projects/main/src/app/views/accounts/account/account.component.html
projects/main/src/app/views/accounts/account/distribution/distribution.component.html
projects/main/src/app/views/accounts/account/staking/staking.component.html
projects/main/src/app/views/accounts/account/txs/txs.component.html
projects/main/src/app/views/blocks/block/block.component.html
projects/main/src/app/views/blocks/blocks.component.html
projects/main/src/app/views/home/bank/bank.component.html
projects/main/src/app/views/home/blocks/blocks.component.html
projects/main/src/app/views/home/distribution/distribution.component.html
projects/main/src/app/views/home/home.component.html
projects/main/src/app/views/home/mint/mint.component.html
projects/main/src/app/views/home/txs/txs.component.html
projects/main/src/app/views/keys/key/key.component.html
projects/main/src/app/views/monitor/monitor.component.html
projects/main/src/app/views/txs/tx/tx.component.html
projects/main/src/app/views/txs/txs.component.html
tailwind.config.js

以下と同じプルリクです。
https://github.com/CauchyE/telescope/pull/298

hotfix: card title margin

---

projects/main/src/app/views/keys/key-backup-dialog/key-backup-dialog.component.ts

I fixed typo in key-backup-dialog.component.ts.
Collect -> Correct
There is no issue for this.

hotfix: collect typo to correct

---

projects/main/src/app/views/accounts/account/account.component.html
projects/main/src/app/views/accounts/account/txs/txs.component.html
projects/main/src/app/views/blocks/blocks.component.html
projects/main/src/app/views/cosmos/bank/bank.component.html
projects/main/src/app/views/cosmos/gov/gov.component.html
projects/main/src/app/views/cosmos/staking/staking.component.html
projects/main/src/app/views/home/bank/bank.component.html
projects/main/src/app/views/home/blocks/blocks.component.html
projects/main/src/app/views/home/distribution/distribution.component.html
projects/main/src/app/views/home/txs/txs.component.html
projects/main/src/app/views/monitor/monitor.component.html
projects/main/src/app/views/txs/txs.component.html

[https://github.com/CauchyE/telescope/issues/220](https://github.com/CauchyE/telescope/issues/220)
の修正です。
以下修正しました。
好みもあるかと思いますので、ご確認お願いいたします。

fix: home and monitor view
