CauchyE/telescope

.github/workflows/docker-cosmoscan.yml

close #42 
docker img作成の順番を変更。
@YasunoriMATSUOKA 確認お願いします。botanyにも同様の変更ありです。
https://github.com/lcnem/botany/pull/48

fix: order of create docker img

---

projects/cosmoscan/src/view/app.component.html
projects/cosmoscan/src/view/cosmos/staking/staking.component.html
projects/cosmoscan/src/view/cosmos/staking/validators/validator/validator.component.html
projects/cosmoscan/src/view/cosmos/staking/validators/validator/validator.component.ts
projects/cosmoscan/src/view/cosmos/staking/validators/validators.component.html

- Stakingメニューを有効化
- Consensus Pubkeyを取得し、hexで表示
- Descriptionの表示についてはMonikerを除いて空データを取得していますが、今後必要になるかと思うので一旦このままにしておきます。
/cosmos/staking/validators/{Valaddress}
@KimuraYu45z 
レビューお願いします。
この部分でまだhogeエラーを吐いている気がするのですが大丈夫でしょうか？
```
ngOnChanges() {
const pubKey = cosmosclient.codec.unpackCosmosAny(this.validator?.consensus_pubkey);
if (!(pubKey instanceof proto.cosmos.crypto.ed25519.PubKey)) {
throw Error('hoge');
}
```

Staking memu

---

projects/cosmoscan/src/app/home/mint/mint.component.html
projects/cosmoscan/src/app/home/mint/mint.component.ts
projects/cosmoscan/src/view/home/mint/mint.component.html
projects/cosmoscan/src/view/home/mint/mint.component.ts

`annual provisions` 現在での予想年間供給のインフレ率
`Inflation`と同じくJPYX-1-testでの動作は現時点では不可能なのでtestchainで動作させています。
@KimuraYu45z @YasunoriMATSUOKA 
`latest-blocks-txs-initial`ブレンチとは無関係の修正です。
レビューお願いします。

feat: annual provisions in top page

---

package-lock.json
package.json
projects/cosmoscan/src/app/blocks/block/block.component.html
projects/cosmoscan/src/app/blocks/block/block.component.ts
projects/cosmoscan/src/view/blocks/block/block.component.html
projects/cosmoscan/src/view/blocks/block/block.component.ts

/blocks/{height}
Blockの詳細ページにValidatorset情報の表示を追加。
ValidatorsetsByHeightを有効化するためにcosmos-client-tsのVersionを更新。

Validator sets

---

projects/cosmoscan/src/app/home/txs/txs.component.ts

#113 にてHTML側で配列を降順にする変更が入ったため、TS側の配列の処理を変更。
現在はWebsocketがJPYXで使用できていないため、コメントアウト中の箇所になります。
```
/* websocket有効化後、自動削除を有効に
this.initialTxs$ = combineLatest([initial, ws.asObservable()]).pipe(
map(([init, latest]) => {
(latest as websocket.ResponseSchema).result.data !== undefined ? (init?.shift()) as CosmosTxV1beta1GetTxsEventResponseTxResponses[] : init;
return init;
}),
);
//*/
```

fix: delete old txs over 20

---

.github/workflows/docker-monitor.yml

CDの修正のため
Push to Docker Hubの際に環境変数を渡すことで`go install . `を通るようにしたい。

fix: docker push

---

projects/main/src/app/models/keys/key-select.guard.ts
projects/main/src/app/models/keys/key.infrastructure.service.ts
projects/main/src/app/models/keys/key.store.service.ts

close #149 
close #150 
@KimuraYu45z cc: @Senna46 @taro04 
レビューお願いします。
Key 選択関連の以下の2個の問題の解決を意図したプルリクです。
1. (bank send等で、)Key Select Dialogで選択したKeyが反映されていない問題
2. (別のページに移動しても)Key Select Dialogが無限に表示され続けるか、Key Select Dialogが一度しか表示されず一度選択するとGUIから別のKeyを選択するすべが無い状況かの2択で、これまで後者の状況に修正していた問題
botany側でcdp関連のデバッグを進めるにも、こちらが正常に動作している必要があり、先にこちらを修正する必要があるという状況で、IndexedDBへの値の読み書きや削除等のエラーハンドリングの修正や、key-select-guardでKeySelectDialogの表示回数に制限をつける等の修正を加えて、解決できたと思うという状況です。

fix: key select related service and guard

---

.github/workflows/docker-monitor.yml
.github/workflows/docker-telescope.yml

Docker Pushが2つあるので、それの区別を容易にするGithub actionの名前の変更のみ

chore: action name

---

projects/monitor/deploy.sh

@KimuraYu45z cc: @Senna46 @taro04 
レビューお願いします。
monitorのデプロイ用のスクリプトを追加しました。
秘密情報を含むconfig.jsonはあらかじめサーバー上に準備しておいて、デプロイ時は `bash deploy.sh` を実行すればOKという想定のスクリプトです。

feat: add script to deploy monitor

---

projects/main/src/app/app.module.ts
projects/main/src/app/models/keys/key-backup-dialog.service.ts
projects/main/src/app/models/keys/key.model.ts
projects/main/src/app/pages/keys/create/create.component.ts
projects/main/src/app/views/keys/key-backup-dialog/key-backup-dialog.component.html
projects/main/src/app/views/keys/key-backup-dialog/key-backup-dialog.component.ts
projects/main/src/app/views/keys/key-backup-dialog/key-backup-dialog.module.ts

作成途中ですが、進捗報告のためPR作成します。
現在ダイアログcomponentとserviceを追加し、ダイアログ閉じるまでアカウント作成の処理を中断するところまで、作成しました。
引き続き、ニーモニックを保存する機能の追加と、保存したか確認するように実装を進めます。

feat: add key backup dialog

---

projects/main/src/app/views/app.component.html
projects/main/src/styles.css

・サイドナビの40px枠に合うように、アイコンのサイズとpaddingを調整します。
（サイズ24pxを40pxに大きくします。アイコン自体の大きさを変えないよう、padding4pxを12pxに調整します。）
・上記変更をtailwindで実装するにあたって、不要と思われる以下のCSSを削除しました。
`.icon {
padding: 4px;
min-width: 0; //削除
width: 24px;
height: 24px;
flex-shrink: 0; //削除
line-height: 40px; //削除
border-radius: 50%; //削除
}`
（単純置換tailwind→class="p-1 min-w-0 w-6 h-6 flex-shrink-0 leading-10 rounded-2xl"）
・アイコンが小さく見えたので、少し大きくしています。
（class="p-3 w-10 h-10”が見た目の大きさを変えない変換。）
お手数ですが、ご確認お願い致します。

Icon height

---

projects/main/src/app/views/accounts/account/account.component.css
projects/main/src/app/views/accounts/account/account.component.html
projects/main/src/app/views/accounts/account/distribution/distribution.component.html
projects/main/src/app/views/accounts/account/staking/staking.component.html
projects/main/src/app/views/cosmos/gov/proposals/proposal/proposal.component.html
projects/main/src/app/views/cosmos/gov/proposals/proposals.component.html
projects/main/src/app/views/cosmos/staking/validators/validator/validator.component.css
projects/main/src/app/views/cosmos/staking/validators/validator/validator.component.html
projects/main/src/app/views/home/bank/bank.component.html
projects/main/src/app/views/home/blocks/blocks.component.html
projects/main/src/app/views/home/distribution/distribution.component.html
projects/main/src/app/views/home/home.component.css
projects/main/src/app/views/home/home.component.html
projects/main/src/app/views/home/mint/mint.component.html
projects/main/src/app/views/monitor/monitor.component.html

column-value, column-nameというclassをtailwindで書き換えました。
赤字(html)がtailwind置換対象のファイル、青字がそもそもcssが設定されていなかったのでタグを削除したファイルです。
参考リンクです。
[margin-left: 0.5rem (8px)](https://tailwindcss.com/docs/margin)
[word-break: break-all](https://tailwindcss.com/docs/word-break)
[white-space: nowrap](https://tailwindcss.com/docs/whitespace)

Del column css

---

projects/main/src/app/pages/keys/create/create.component.ts
projects/main/src/app/views/blocks/blocks.component.html
projects/main/src/app/views/keys/create/create.component.html
projects/main/src/app/views/keys/create/create.component.ts
projects/main/src/app/views/keys/key-backup-dialog/key-backup-dialog.component.html
projects/main/src/app/views/keys/key-backup-dialog/key-backup-dialog.component.ts

・accout作成時のニーモニックを貼り付けてアカウントを作成すると、DLしたファイルのニーモニックが空欄であるバグの修正。
・その他、Blocks画面のタイトル変更。英文の大文字、小文字の整理。
ニーモニックから作成したアカウント（aaaa2）でも、DLしたファイルにニーモニックが記載されていることを確認しました。
[key-aaaaa-2021118213147.txt(オリジナル)](https://github.com/lcnem/telescope/files/7497015/key-aaaaa-2021118213147.txt)
[key-aaaa2-2021118213219.txt(コピー)](https://github.com/lcnem/telescope/files/7497018/key-aaaa2-2021118213219.txt)
動いてはいますが、viewsのcreateコンポーネントからdialogを呼び出した方が素直なような気もしています。
必要であれば修正しますので、コメントお願いいたします。

Fix create dialog

---

.vscode/extensions.json
projects/main/src/app/pages/accounts/account/account.component.html
projects/main/src/app/pages/accounts/account/account.component.ts
projects/main/src/app/pages/accounts/account/distribution/distribution.component.html
projects/main/src/app/pages/accounts/account/distribution/distribution.component.ts
projects/main/src/app/pages/accounts/account/staking/staking.component.html
projects/main/src/app/pages/accounts/account/staking/staking.component.ts
projects/main/src/app/views/accounts/account/distribution/distribution.component.html
projects/main/src/app/views/accounts/account/distribution/distribution.component.ts
projects/main/src/app/views/accounts/account/staking/staking.component.html
projects/main/src/app/views/accounts/account/staking/staking.component.ts
projects/main/src/app/views/cosmos/staking/validators/validator/validator.component.html

@taro04 cc: @KimuraYu45z 
https://github.com/lcnem/telescope/pull/197 のプルリクの件、自分だったらこういう方針の修正を考えるという一例としてプルリク作成してみました。レビューして頂き問題無ければマージして、作業進めてくださればと思います。こちらでのデバッグは甘めなので、慎重にレビューしてもらえると助かります。
意図としては、今回気づいてくださったように、クエリパラメーターから与えられるアドレスは、必ずしも有効なアドレスでない場合があり、その場合accAddressに変換するところでエラーが発生していて、そのエラーが適切にハンドリングされていないことは、そもそも根本的に問題であったと思うので、この機会に修正しませんかという意図です。(undefinedなアドレス値をcosmos-client-tsに渡してAPIたたこうとする処理が走ってしまうと、そこで無駄にエラーが起きてしまうでしょうし、もし無効な値をセットしてAPIたたかれる状況等があれば、その分無駄が発生してしまうでしょうし、避けられるなら避けたほうが良いと思います。)
また、(既に書かれたコード、最近のコミット双方ともに)タイポが散見されることから、VSCodeの設定ファイルに推奨extensionとしてcode spell checkerを追加してみました。差分で追加されている拡張機能を入れて、青い波線ついているところは、何かtypoしていないか等、意識してみてください。
また、賛否両論あったりケースバイケースかもしれませんが、エディタの入力補完が便利になった昨今では、変数名を省略してキータイプの手数を減らすよりも、わかりやすい変数名を使ってエディタの入力補完を使用したほうが、コーディングスピードと可読性を両立できるという点で望ましいのではないかと …

feat: add error handling to account info page and fix

---

projects/main/src/app/pages/txs/txs.component.ts

close #201 
Tx数の少ないもので、`modifiedPageOffset`=`modifiedPageSize`となり、400エラーが返ってくる問題の修正。
pageOffset < 1のとき
変更前
modifiedPageOffset, modifiedPageSize = 1,1
変更後
modifiedPageOffset, modifiedPageSize = 1,2

fix: irregular pagination tx total count 1 page offset 1 page limitation 1 with work around way

---

projects/main/src/app/app.module.ts
projects/main/src/app/models/keys/key-delete-dialog.service.ts
projects/main/src/app/models/keys/key.application.service.ts
projects/main/src/app/pages/keys/keys.module.ts
projects/main/src/app/views/keys/key-delete-confirm-dialog/key-delete-confirm-dialog.component.html
projects/main/src/app/views/keys/key-delete-confirm-dialog/key-delete-confirm-dialog.component.ts
projects/main/src/app/views/keys/key-delete-confirm-dialog/key-delete-confirm-dialog.module.ts
projects/main/src/app/views/keys/key-delete-dialog/key-delete-dialog.component.html
projects/main/src/app/views/keys/key-delete-dialog/key-delete-dialog.component.ts
projects/main/src/app/views/keys/key-delete-dialog/key-delete-dialog.module.ts
projects/main/src/app/views/keys/key/key.component.html
projects/main/src/app/views/keys/key/key.component.ts

製作途中ですが、進捗報告かねPR作成します。作成したアカウント機能の追加タスクです。
・/keys/:key_idページの上端右端にDeleteボタンを追加。
　（このボタンはあえてゴミ箱のアイコンだけにしています。さすがに分かりにくいでしょうか？
　　そうであればCreateと同じようにflatボタン＋iconに修正します。）
・アカウント削除ダイアログ追加。
・idの判定と判定結果のスナックバー表示追加
明日以降実際のアカウント削除の実装をします。

feat: add account delete dialog

---

projects/main/src/app/models/cosmos/bank.application.service.ts
projects/main/src/app/models/cosmos/bank.service.ts
projects/main/src/app/pages/cosmos/bank/send/send.component.html
projects/main/src/app/pages/cosmos/bank/send/send.component.ts
projects/main/src/app/views/cosmos/bank/send/send.component.html
projects/main/src/app/views/cosmos/bank/send/send.component.ts

close #207 
#222 も一部解決
bank.application.serviceにて、返ってきたtx_response.codeによってエラーを吐く仕様に変更。
そのため。間違ったDenomなどの場合にtx_response.raw_logをSnackBarに表示しています。
> HTML上でプルダウンリストにする
denomの選択について本PRでは対応していませんが、もし必要であればコメントお願いします。
'invalid coin'のエラーは出るので不要な気もします。
@YasunoriMATSUOKA 確認お願いします。

feat: bank send tx error handling and improve ui ux

---

projects/main/config.js.template
projects/main/src/app/app.module.ts
projects/main/src/app/models/config.service.ts
projects/main/src/app/models/cosmos/bank.application.service.ts
projects/main/src/app/models/cosmos/bank.model.ts
projects/main/src/app/models/cosmos/bank.service.ts
projects/main/src/app/models/cosmos/tx-common.model.ts
projects/main/src/app/models/cosmos/tx-common.service.ts
projects/main/src/app/pages/cosmos/bank/send/send.component.html
projects/main/src/app/pages/cosmos/bank/send/send.component.ts
projects/main/src/app/views/cosmos/bank/send/send.component.html
projects/main/src/app/views/cosmos/bank/send/send.component.ts
projects/main/src/app/views/cosmos/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.html
projects/main/src/app/views/cosmos/tx-fee-confirm-dialog/tx-fee-confirm-dialog.component.ts
projects/main/src/app/views/cosmos/tx-fee-confirm-dialog/tx-fee-confirm-dialog.module.ts
projects/main/src/app/views/keys/key-select-dialog/key-select-dialog.component.html
projects/main/src/app/views/material.module.ts

@KimuraYu45z 
トランザクションのアナウンスの前に、simulateのAPIを叩くような意図で、このプルリクのような形で実装してみたのですが、以下エラーを解決できない状態で詰まっています。いったんこのプルリクで現状の記録を残しておきます。
```
./projects/main/src/app/models/cosmos/bank.service.ts:3:0-92 - Error: Module not found: Error: Package path ./esm/openapi/api is not exported from package /home/yasunori_matsuoka/src/github.com/lcnem/telescope/node_modules/@cosmos-client/core (see exports field in /home/yasunori_matsuoka/src/github.com/lcnem/telescope/node_modules/@cosmos-client/core/package.json)
```

feat: add simulation request to tx bank send

---

projects/main/src/app/views/blocks/block/block.component.html
projects/main/src/app/views/home/bank/bank.component.html
projects/main/src/app/views/home/blocks/blocks.component.html
projects/main/src/app/views/home/distribution/distribution.component.html
projects/main/src/app/views/home/home.component.html
projects/main/src/app/views/home/txs/txs.component.html
projects/main/src/app/views/txs/tx/tx.component.html

[https://github.com/lcnem/telescope/issues/215](https://github.com/lcnem/telescope/issues/215)の修正です。
以下の記事を参考に実装しました。
[https://dev.classmethod.jp/articles/mat-divider-last-hidden/](https://dev.classmethod.jp/articles/mat-divider-last-hidden/)
レイアウト見てhome、Transaction詳細、Block詳細ページ以外のページはdividerが必要だと感じたので、
home、Transaction詳細、Block詳細ページのみ修正を行いました。
同様にhomeページ、Transactionのカードは、pagenationとの区別にdividerが必要だと思ったので
こちらも削除していません。
実装結果です。
また、カードが連続している部分のレイアウトを見直しました。
ご確認お願い致します。

feat: delete last element divider

---

projects/main/src/app/pages/home/blocks/blocks.component.ts
projects/main/src/app/views/blocks/blocks.component.html
projects/main/src/app/views/home/blocks/blocks.component.html
projects/main/src/app/views/home/txs/txs.component.html
projects/main/src/app/views/txs/txs.component.html

[https://github.com/lcnem/telescope/issues/219](https://github.com/lcnem/telescope/issues/219)
こちらのIssue対応です。
htmlファイルでTx、Blocksのリストの先頭行はmat-nav-listではなく、mat-listとなるよう調整しました。
ローカル環境では、動作とレイアウトが崩れていないこと確認しています。ご確認お願い致します。

feat: disable click action at first item on tx and blocks table

---

projects/main/src/app/models/cosmos/bank.application.service.ts
projects/main/src/app/models/cosmos/staking.application.service.ts

@KimuraYu45z 
レビューお願いします。
REST APIにアクセス集中していないときはsimulateのAPIレスポンスは比較的すぐ返ってくるのでこれまであまり気にならなかったのですが、REST APIにアクセス集中しているときはsimulateのAPIのレスポンスもそれなりに待ち時間が発生するようで、simulateのAPIのレスポンスの待ち時間の際loading dialogを表示していなかったので、ボタンを押せていないと勘違いして何度もトランザクション送信ボタンを押してしまうパターンの問題があったようで、その対策の修正です。UnUniFi/utilsの方も同様に修正しておこうと思います。

feat: add loading dialog to simulation

---

projects/main/src/app/views/home/home.component.html

[https://github.com/CauchyE/telescope/issues/246](https://github.com/CauchyE/telescope/issues/246)の修正です。
以下の通り表示追加しました。
ご確認お願い致します。

fix: add (chain_id) to Network in home page

---

projects/main/src/app/models/cosmos/bank.application.service.ts
projects/main/src/app/models/cosmos/bank.service.ts

[https://github.com/CauchyE/telescope/issues/248](https://github.com/CauchyE/telescope/issues/248)の修正です。
bank/send で秘密鍵を入力する際に、空白文字を切るように、以下と同様に修正しました。
[https://github.com/CauchyE/telescope/pull/247](https://github.com/CauchyE/telescope/pull/247)
ローカルで秘密鍵の前後にスペースを付加して動作確認しました。ご確認お願い致します。

feat: remove unintentional whitespace in private key

---

projects/main/src/app/models/cosmos/bank.service.ts
projects/main/src/app/models/keys/key.service.ts
projects/main/src/app/pages/keys/create/create.component.ts

[https://github.com/UnUniFi/utils/pull/190](https://github.com/UnUniFi/utils/pull/190)の逆輸入です。
＜変更点＞
・秘密鍵から空白文字を除く実装をbankServiceからkeyServiceに移動。
・同時に公開鍵の空白文字削除と、ニーモニックの前後の空白文字削除。
＜デバック＞
修正箇所はkeyServiceの以下４つのメソッドで、
以下の通り動作に問題ないことを確認しました。
getPrivkey⇒
bank/sendで空白文字を入れた秘密鍵で送信できることを確認。
getPubkey⇒
ユーザー入力で使用する箇所なし。
sign⇒
keys/signで空白文字を入れた秘密鍵を入力し、空白文字に関係なく、signature(Base64)の表示が変わらないことを確認。
getPrivateKeyFormMnemonic⇒
bank/createで空白文字を入れたニーモニックでアカウントを作成し、confirmダイアログの認証が通ることを確認。

fix: remove whitespace in keyservice

---

projects/main/src/app/views/accounts/account/account.component.html
projects/main/src/app/views/accounts/account/distribution/distribution.component.html
projects/main/src/app/views/accounts/account/staking/staking.component.html
projects/main/src/app/views/accounts/account/txs/txs.component.html
projects/main/src/app/views/blocks/block/block.component.html
projects/main/src/app/views/blocks/blocks.component.html
projects/main/src/app/views/home/bank/bank.component.html
projects/main/src/app/views/home/blocks/blocks.component.html
projects/main/src/app/views/home/distribution/distribution.component.html
projects/main/src/app/views/home/home.component.html
projects/main/src/app/views/home/mint/mint.component.html
projects/main/src/app/views/home/txs/txs.component.html
projects/main/src/app/views/keys/key/key.component.html
projects/main/src/app/views/monitor/monitor.component.html
projects/main/src/app/views/txs/tx/tx.component.html
projects/main/src/app/views/txs/txs.component.html
tailwind.config.js

[https://github.com/CauchyE/telescope/issues/220
](https://github.com/CauchyE/telescope/issues/220)
の修正です。
mat-cardとタイトルの上下の余白を調整しました。
・基本はカード間は1rem （カードの内容によっては調整）
・カードとタイトル間は０
・カードタイトルのサイズをh3からh2へ統一。
デバック途中の箇所あるので、
次回確認後、レビューをお願いさせていただきます。

fix: card title margin
